# MapR client(s) running in a Docker container
#
# VERSION 0.1 - not for production, use at own risk
#

#
# Use the MapR Client image as the base
FROM mkieboom/mapr-client

MAINTAINER mkieboom @ mapr.com

# CUSTOM DOCKER COMMANDS HERE

# TODO: Avoid users to switch back to root, eg:
USER root

# Keep container running
CMD /bin/bash